config/routes.rb
# -*- encoding : utf-8 -*-
require 'sidekiq/web'
Shangjieba::Application.routes.draw do
  resources :bshows


  resources :games


  resources :cards


  resources :redpacks


  resources :ibeacons


  mount SjbApi => '/'
  mount Sidekiq::Web => '/sidekiq'
  resources :tracks


  namespace :shangou do
    resources :users
  end


  resources :honours

  resources :user_activities

  get 'matters/:id/view_show' => 'matters#view_show'
  get 'matters/new_matter' => 'matters#new_matter'

  resources :matters

  namespace :m do
    root :to => "welcome#index"
  end

  get "welcome/index"

  get "welcome/m"

  get "/welcome/friend_apps" => "welcome#friend_apps"
  get "/welcome/friend_weixins" => "welcome#friend_weixins"
  post "/welcome/go_download" => "welcome#go_download"

  get "/users/:id/grow_info" => "users#info"

  namespace :monitor do
    root to: "welcome#index"
    get "welcome/home" => "welcome#home"
    get "welcome/expire_index" => "welcome#expire_index"
  end


  resources :notify, only: [] do
    collection do
      post :alipay
      post :wxpay
    end
  end

  namespace :manage do
    root to: "home#index"
    resources :friend_apps
    
    resources :synonyms
    resources :posts do
      member do
        get :photo
        post :photo_create
      end
    end

    post "/posts/:id" => "posts#update"
    resources :tags do
      member do
        get :get_desc
      end
    end

    resources :all_tags
    get '/dapeis/queue' => "dapeis#queue"
    get '/collections' => "dapeis#collections"
    get '/selfies' => "dapeis#selfies"
    get '/dapeis/:id/new_comment' => "dapeis#new_comment"
    put '/selfy/:id', to: 'dapeis#selfy_update', as: :selfy
    resources :collections do
      member do
        post :cover_photo # 封面图
      end
      resources :comments, :only => [:index, :create, :destroy], :name_prefix => "item_"
    end

    resources :selfies ,:only =>[:new,:create]
    # resources :dapeis
    resources :dapeis do
      collection do
        get 'all'
      end

      member do
        post 'recommend_star'
        post 'unrecommend_star'
      end
    end

    put "categories/set_app_photo" => "categories#set_app_photo"

    resources :categories do
      collection do
        get :for_select
        get :ajax_select_change
      end

      member do
        get :feature
        post :feature_create
      end
    end
    resources :matters do
      collection do
        get :recommends
        get :brands
        get :tags
        post :recommended
      end
    end

    get 'matters/:id/koutu' => "matters#koutu"
    get 'user_behaviours/:user_id' => "user_behaviours#index"
    get 'user_behaviours/xml_index/:user_token' => "user_behaviours#xml_index"
    resources :user_behaviours
    resources :matter_tags
    resources :meta_tags

    resources :dapei_tags do
      member do
        post :upload
      end
    end

    resources :apps
    resources :photos, only: :destroy
    resources :flinks
    resources :crawler_templates do
      collection do
        get "search_brands"
        get "search_malls"
      end
    end
    resources :users, except: :new do
      member do
        get :set_black
        get :set_v
      end
      resources :messages
    end

    resources :malls
    resources :discounts
    resources :spiders, except: :new do
      member do
        get :start_crawl
        get :start_soldout
        get :update_state
      end
      resources :spider_pages
    end
    post '/spiders/:spider_id/spider_pages' => 'spider_pages#create', :as => 'spider_spider_pages_index'


    resources :tshow_spiders, except: :new do
      member do
        get :start_crawl
      end
    end
    resources :brand_tags
    resources :brands do
      resources :spiders, only: :new
      resources :tshow_spiders, only: :new
      member do
        get :spiders
        post :upload
      end
    end

    resources :shops do
      member do
        get :discounts
      end
    end

    resources :feedbacks
    resources :lotteries

    get "update_category_photo/:category_id/:matter_id" => "categories#set_photo", :as => "update_category_photo"
  end


  namespace :service do
    get "dapei/get_color" => "dapei#get_color"
    get "dapei/template_cut" => "dapei#template_cut"
    get "dapei/cut_templates" => "dapei#cut_templates"
  end

  resources :daren_applies do
    collection do
      get "about_daren"
      get "user_help"
      get "daren_info"
      get "medal_info"
    end
  end  

  scope "sjb" do
    resources :relations

    resources :labels

    resources :policies

    resources :user_devices

    resources :user_exts do
      collection do
        get :new_create
      end
    end

    get "user_exts/new_create/fr/android" => "user_exts#new_create"
    get "user_exts/create_result" => "user_exts#create_result"


    resources :lotteries

    resources :join_lotteries
    get "join_lottery/status" => "join_lotteries#status"
    get "lottery/current" => "lotteries#current"

    get "cj" => "user_exts#cj"
    get "reg" => "user_exts#reg"
    get "daren_apply_status" => "daren_applies#show"

  end

  get "app/test/app_about" => "about#app_about", :as => "app_about"
  get "app/test/app_business" => "about#app_business", :as => "app_business"
  get "web/web_version" => "home#index", :as => "web_version"


  get "weixin/app" => "weixin#app"
  get "weixin/sg_app" => "weixin#sg_app"
  get "weixin/app" => "weixin#app"
  get "app/android" => "weixin#android_download"

  get "about/info/brand_all" => "about#brand_all"

  get "about/info/fashion" => "about#fashion"

  get "about/info/website_map" => "about#website_map"

  get "about/info/trade" => "about#trade"

  get "about/info/member_introduce" => "about#member_introduce"

  get "about/info/get_password" => "about#get_password"

  get "about/info/help" => "about#help"

  get "about/info/report" => "about#report"

  get "about/info/recruitment" => "about#recruitment"

  get "about/info/brand_enter" => "about#brand_enter"

  get "about/info/collaborate" => "about#collaborate"

  get "about/info/advertisement" => "about#advertisement"

  get "about/info/merchant" => "about#merchant"

  get "about/info/contact" => "about#contact"
  get "about/info/cover" => "about#cover"
  get "about/info/mzsm" => "about#mzsm"

  get "about/shangou_option" => "about#shangou_option"

  get "collocations/mask_spec" => "collocations#mask_spec"
  get "collocations/text2image" => "collocations#text2image"

  get "collocations/hot_dapei_tags" => "collocations#hot_dapei_tags"
  get "info/hot_dapei_tags" => "collocations#hot_dapei_tags"
  get "info/publish_dapei_tags" => "collocations#publish_dapei_tags"
  get "info/dapei_themes" => "collocations#dapei_themes"
  get "info/app_banner" => "about#app_banner"
  get "info/app_banner_new" => "about#app_banner_new"
  get "info/dapei_banners" => "about#dapei_banners"

  get "info/daren_policy" => "policies#daren"
  get "info/dapei_tags" => "about#dapei_tags"


  get "info/activity_types" => "discounts#discount_types"

  resources :collocations do
    collection do
      get 'price_range'
      get 'app_template'
    end
  end


  get 'cgi/mystuff.things' => "collocations#mystuff_things"
  get 'cgi/like_matters' => "collocations#like_matters"

  post 'cgi/set.draft' => "collocations#set_draft"
  post 'cgi/template.publish' => "collocations#template_publish"
  post 'cgi/stats.record' => "collocations#stats_record"

  post 'cgi/favorite.add_thing' => "likes#create"
  post 'cgi/favorite.delete_thing' => "collocations#delete_thing"
  post 'cgi/favorite.delete_matter' => "collocations#delete_matter"

  get 'cgi/autocomplete.user_tagging' => "collocations#user_tagging"
  get 'cgi/autocomplete.user_hashtags' => "collocations#user_hastags"
  get 'cgi/autocomplete.price_ranges' => "collocations#price_ranges"
  get 'cgi/autocomplete.category_id_titles' => "collocations#category_id_titles"
  get 'cgi/autocomplete.categories' => "collocations#categories"
  get 'cgi/autocomplete.editor' => "collocations#editor"
  get 'cgi/template.load' => "collocations#template_load"
  get 'cgi/search.editor_things' => "collocations#editor_things"
  get 'cgi/search.sponsored_things' => "collocations#sponsored_things"
  get 'cgi/search.templates' => "collocations#templates"
  # post "/cgi/login.login" => "collocations#login_login"
  # get 'cgi/login' => "collocations#login"
  post "cgi/set.publish" => "collocations#publish"
  get "cgi/autocomplete.shop" => "collocations#shop"
  get 'cgi/collection.load' => "collocations#collection_load"

  get 'cgi/set.embed_html' => "collocations#embed_html"
  get 'cgi/autocomplete.tag_trends' => "collocations#tag_trends"
  get 'cgi/set.load' => "collocations#cgi_set_load"
  get 'cgi/set' => "collocations#cgi_set"

  get "dapeis/cgi/autocomplete.shop" => "collocations#shop"
  post "dapeis/cgi/stats.record" => "collocations#stats_record"
  get "dapeis/cgi/collection.load" => "collocations#collection_load"
  post 'cgi/comment.add' => "collocations#comment_add"

  get "cgi/item" => "collocations#item"
  get "cgi/collection.get" => "collocations#collection_get"
  get "cgi/mystuff.sets" => "collocations#mystuff_sets"
  get "cgi/mystuff.drafts" => "collocations#mystuff_drafts"
  get "cgi/mystuff.templates" => "collocations#mystuff_templates"
  get "uploads//cgi/img-thing/mask_spec/:spec/size/orig/tid/:image_name" => "collocations#mask_sepc"

  post "cgi/app.save_mask" => "collocations#save_mask"
  get "cgi/app.get_masks" => "collocations#get_masks"
  get "cgi/cut_templates" => "collocations#cut_templates"

  scope "admin" do
    resources :flinks
  end

  get "brands/info/web_index" => "brands#web_index", :as => "brands_web_index_old"
  get "brands/info/:id" => "brands#web_show", :as => "brands_web_show_old"

  resources :brands, :only => [:show]

  resources :recommends, :except => [:index]

  get "categories/index"
  get "about/feedback" => "about#feedback", :as => "feedback"

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  before_filter :load_flinks
  #before_filter :load_area

  def index
    @shops = Shop.cache_recommend_shops_by_city_id(@city_id)
    
    @baobei = Sku.cache_recommend_sku_by_category_id(1)

    @shangzhuang=Sku.cache_recommend_sku_by_category_id(11)
    @kuzhuang=Sku.cache_recommend_sku_by_category_id(12)
    @qunzhuang=Sku.cache_recommend_sku_by_category_id(13)
    @neiyi = Sku.cache_recommend_sku_by_category_id(14)
    @xiezi=Sku.cache_recommend_sku_by_category_id(4)
    @baobao=Sku.cache_recommend_sku_by_category_id(5)
    @peishi=Sku.cache_recommend_sku_by_category_id(6)
    @nanzhuang=Sku.cache_recommend_sku_by_category_id(7)
    @tongzhuang =Sku.cache_recommend_sku_by_category_id(8)

    @lookbook = Sku.cache_recommended_lookbooks

    @dapei = Dapei.cache_recommended_all_by_category_id(1001)

    @sale_items = Searcher.new(nil, "item", "", "sale", 6).search()
    @brands = Brand.cache_brands_level_bigger_than(4)

    @wide3brands=@brands.first(3)
    @squre6brands=@brands.last(6)
    @normal9brands=@brands[3,9]
    @recommended_streets=Recommend.cache_recommended_streets_by_city_id(@city_id)
    @users=User.cache_recommended_by_city_id(@city_id)
    render :layout=>"home_2013"
  end

  def appmain
    @page = 1
    searcher = Searcher.new(nil, "dapei", nil,  "new", 50, @page)
    @dapeis = searcher.search()
    @dapeis = Dapei.dup(@dapeis)
    @dapeis = @dapeis.first(12)

    #@app_info = AppInfo.find(1)
    #@apk_url = @app_info.download_url

    render :template => "home/home", :layout => false

  end

  def citylist
    render :layout=>"home_2013"
  end

  def app
    render :layout=>"new_app"
  end

  def redirect
    if params[:url]
      redirect_to params[:url]
    end
  end

  def check_update
    sku_updated_at = Tagging.maximum('created_at').to_i 
    if Category.maximum('updated_at').to_i > Tagging.maximum('created_at').to_i 
      sku_updated_at = Category.maximum('updated_at').to_i
    end
    
    update =
        {
           :item_category =>  Category.maximum('updated_at').to_i,
           :dapei_tags => DapeiTag.maximum('updated_at').to_i,
           #:matter_category => Category.maximum('updated_at').to_i,
           :matter_category => Time.now.to_i,
           :brand_list => Brand.maximum('updated_at').to_i,
           :brand_tags => BrandTag.maximum('updated_at').to_i,
           :sku_tags => sku_updated_at,
           :show_wanhuir => 1,
           :use_yjs => 0,
           :share_change => 0.2,
           :all => 0
        }
    render :json => {:update => update, :success => true}
  end

  def check_update_new
    sku_updated_at = Tagging.maximum('created_at').to_i
    if Category.maximum('updated_at').to_i > Tagging.maximum('created_at').to_i
      sku_updated_at = Category.maximum('updated_at').to_i
    end

    update =
        {
           :item_category =>  Category.maximum('updated_at').to_i,
           :dapei_tags => DapeiTag.maximum('updated_at').to_i,
           #:matter_category => Category.maximum('updated_at').to_i,
           :matter_category => Category.maximum('updated_at').to_i,
           :brand_list => Brand.maximum('updated_at').to_i,
           :brand_tags => BrandTag.maximum('updated_at').to_i,
           :sku_tags => sku_updated_at,
           :show_wanhuir => 1,
           :use_yjs => 0,
           :share_change => 0.01,
           :all => 0
        }
    render :json => {:update => update, :success => true}
  end


end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/views/home/_area_nav.html.haml
.nav_area
  .l 附近逛逛：
  .c
    %ul
      -num=0
      -@dists.each do |dist|
        -num=num+1
        %li.nav_b
          / 添加hover后显示层
          .showChaoyangCounts.menu
            %a.menu-hd{:href => "#{search_path('shop', '', dist.dp_id)}", :num=>"#{num}", :dp_id=>"#{dist.dp_id}"}
              #{dist.name}
              %b
    #chaoyangCounts.area-layer{:style => "display:none"}
      %ul.panel
  -#.r
    -#%span 
      %b
    -#%span >>

app/views/home/_hot_brand.html.haml
.wrapper
  .big-sale.chunk.chunk-three
    .chunk-head
      .head-img
        %img{:src => "/assets/newweb/hot_brand.png", :alt=>"#{@city}品牌", :title => "#{@city}品牌"}
    .chunk-three-body
      %ul.nav.nav-float.chunk-three-ul.chunk-three-ul-one
        -@wide3brands.each do |wb|
          -#- if wb == @wide3brands.last
            %li{:id => "ul-last-li"}
              .three-top
                %a{:href=>"#{brands_web_show_path(wb)}"}
                  %img{:src => "#{wb.banner_url}"}
                    .opacity-tiny-b
                      #{wb.get_display_name.capitalize}
          -#- else
          %li
            .three-top
              %a{:href=>"#{brands_web_show_path(wb)}"}
                %img{:src => "#{wb.banner_url}", :alt=>"#{brand_alt(wb)}", :title=>"#{brand_title(wb)}"}
                  .opacity-tiny-b
                    #{wb.get_display_name.capitalize}
          
      %ul.nav.nav-float.chunk-three-ul.chunk-three-ul-two
        -unless @normal9brands.blank?
          -@normal9brands.each do |nb|
            - if nb == @normal9brands.last
              %li{:id => "ul-last-li"}
                %a{:href=>"#{brands_web_show_path(nb)}"}
                  %img{:src => "#{nb.high_campaign_img(:normal_medium)}", :alt=>"#{brand_alt(nb)}", :title=>"#{brand_title(nb)}"}
                    .opacity-tiny
                      #{nb.get_display_name.capitalize}
            - else
              %li
                %a{:href=>"#{brands_web_show_path(nb)}"}
                  %img{:src => "#{nb.high_campaign_img(:normal_medium)}", :alt=>"#{brand_alt(nb)}",  :title=>"#{brand_title(nb)}"}
                    .opacity-tiny
                      #{nb.get_display_name.capitalize}
      %ul.nav.nav-float.chunk-three-ul.chunk-three-ul-three
        -@squre6brands.each do |sb|
          - if sb == @squre6brands.last
            %li{:id => "ul-last-li"}
              %a{:href=>"#{brands_web_show_path(sb)}"}
                %img{:src => "#{sb.high_campaign_img(:thumb_medium)}", :alt=>"#{brand_alt(sb)}",  :title=>"#{brand_title(sb)}"}
                  .opacity-square
                    #{sb.get_display_name.capitalize}
          - else
            %li
              %a{:href=>"#{brands_web_show_path(sb)}"}
                %img{:src => "#{sb.high_campaign_img(:thumb_medium)}", :alt=>"#{brand_alt(sb)}",  :title=>"#{brand_title(sb)}"}
                  .opacity-square
                    #{sb.get_display_name.capitalize}

app/views/home/_hot_dapei.html.haml
.wrapper
  .big-sale.chunk.chunk-four
    .chunk-head
      .head-img
        %img{:src => "/assets/newweb/hot_dapei.png", :alt => "热门搭配", :title => "热门品牌"}
    .chunk-four-body
      %ul.nav.nav-float.chunk-four-ul
        - @dapei.each do |dp|
          %li
            %a{:href => "#{dapei_view_path(dp)}"}
              %img{:src => "#{dp.dapei_img_url()}", :alt=>"#{dapei_photo_alt(dp)}", :title => "#{dapei_photo_title(dp)}"}
                .opacity-dapei
                  .item-brand
                    #{dp.title}搭配
                  .item-title
                    /By holder
                    By #{dp.get_user_name}
                  .item-date
                    #{dp.upload_date1}

app/views/home/_hot_shop.html.haml
.wrapper
  .big-sale.chunk.chunk-two
    .chunk-head
      .head-img
        %img{:src => "/assets/newweb/hot_shop.png", :alt => "#{@city}打折", :title => "#{@city}打折"}
    .chunk-two-body
      %ul.nav.nav-float.chunk-two-ul
        - @sale_items.each do |item|
          - unless item.blank?
            %li
              %a{:href => "#{brand_baobei_path(item.brand,item)}", :target=>"_blank"}
                %img{:src => "#{item.img_url(:normal_medium)}", :alt=>"#{@city}#{item.brand_name.capitalize}打折 #{@city}打折", :title=>"#{@city}#{item.brand_name.capitalize}打折 #{@city}打折"}
                  .opacity-big
                    .item-brand
                      #{item.brand_name.capitalize}
                    .item-price
                      %span.price
                        %span.price-two #{item.get_currency}
                        %span.new-price
                          #{item.get_num_price}
                        %span.old-price
                          #{item.get_num_origin_price}
                    -#.item-adress
                      #{item.shop_street}
      -#%ul.nav.nav-float.chunk-two-ul-bottom
        -@discounts.each do |discount|
          =render :partial=>'recommend_discount_item', :locals=>{:discount=>discount}

/ 2F
-#.recom-p.clearfix.gjb_2
  .hd
    %h2 推荐热店
    %a.more{:href => "#{search_path}"} more
  -#%a.previous{:href => "#"}
  -#%a.next{:href => "#"}
  .bd
    %div
      %ul
        -number=0
        -@shops.each do |shop|
          -if number>3
            -break
          -number=number+1
          =render :partial=>"/home/recommend_shop_item", :locals=>{:shop=>shop}
      %dl
        %dt
          -#优惠活动
          -#%b
        -i=0
        -num=5
        -@discounts.each do |discount|
          -break unless i<num
          -if discount.discountable_type=="Shop" and discount.is_current?
            =render :partial=>"/home/recommend_discount_item", :locals=>{:discount=>discount}
            -i=i+1

app/views/home/_recommend_daren_item.html.haml
%li
  %a{:href => "#{user_path(user)}", :title=>"#{user.display_name}"}
    %img{:height => "50", :src => "#{user.display_img_small}", :width => "50", :alt=>user.name}/

app/views/home/_recommend_street_item.html.haml
%li
  .intro  
    %a{:href => "#{search_path("", "", "", "", "", street_recommend.name)}" }
      #{street_recommend.reason}
      / %b.hot
  %div{:class=>"name #{type}"}
    %a{:href => "#{search_path("", "", "", "", "", street_recommend.name)}" }
      #{street_recommend.name}

app/views/home/appmain.html.erb
<html><head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="renderer" content="webkit">

<meta name="keywords" content="上街吧,时尚,打折,优惠,搭配,搭配工具,女装,包包,鞋子,配饰,服饰,热店,品牌,女装,女包,女鞋,男装,童装,化妆品,app">
<meta name="description" content="上街吧,帮助爱美女性发现时尚，创建自己的时尚范儿。是女性用户首选的时装购物平台,方便快捷获取最新款时尚女装、包包、鞋子、配饰及其周边热门品牌新品、打折、优惠信息，轻松制作搭配，分享搭配心得和美丽经验。">
<title>上街吧-时尚品牌穿衣助手,美丽搭配DIY.</title>
<script>
    var is_iPd = navigator.userAgent.match(/(iPad|iPod|iPhone)/i) != null;
    var is_mobi = navigator.userAgent.toLowerCase().match(/(ipod|iphone|android|coolpad|mmp|smartphone|midp|wap|xoom|symbian|j2me|blackberry|win ce)/i) != null;
    if(is_mobi && window.location.search.indexOf("m=true")<0){
      //window.location.href="http://m.shangjieba.com";
    }
</script>
<link rel="icon" href="/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link href="/app_main_css/style.min.css" rel="stylesheet">
<link href="/app_main_css/zh-skin.css" rel="stylesheet">
<!--<%= stylesheet_link_tag "application_2013", :media => "all"%>-->
<%= javascript_include_tag "basic"%>
  <!--[if lte IE 6]>
  <link rel="stylesheet" type="text/css" href="/app_main_css/ie6.min.css">
  <link rel="stylesheet" type="text/css" href="/app_main_css/ie.css">
  <![endif]-->
<link rel="stylesheet" href="http://zhushou.360.cn/pop/style/pop_0411.css" id="zsp_css" media="all" type="text/css"></head>


<body class="welcome" style="">

<div class="times" style="display:none;">
  <div class="endtime" value="1386216000">上街吧全新3.0已隆重发布!</div>
  <p><a href="/20131205">☆☆☆有奖活动猛击这里☆☆☆</a></p>
</div>

<div class="carousel">
  <div class="navbar-wrapper">
    <div class="container">
      <a href="/" class="navbar-logo pull-left"></a>

      <ul class="navbar-menu nav nav-pills pull-right">
        <li><a href="/">首页</a><span>|</span></li>
        <li><a href="<%=app_about_path%>">关于我们</a><span>|</span></li>
        <%- if user_signed_in? %>
          <li><a href = "<%=user_path(current_user)%>">
               已登录, <%= current_user.display_name%>
          </a><span>|</span></li>
        <%- else %>
          <li><a href="<%=new_user_session_path%>" target="_blank">登录</a><span>|</span></li>
        <%- end %>
        <%- if user_signed_in? %>
          <li><a href = "/dapeis/index_all" target="_blank"> +发布搭配</a></li>
        <%-else%>
          <li><a href = "<%=search_path('dapei')%>" target="_blank"> +发布搭配</a></li>
        <%- end%>
      </ul>
    </div>
  </div>

  <div class="container carousel-banner">
    <div class="intro-left pull-left">
      <h2>穿出你的时尚范儿</h2>
      <h3>紧跟1000+时装品牌的脚步</h3>
      <h3>时尚搭配DIY,轻松分享自己的style</h3>
      <!--
      <button type="button" class="btn btn-success btn-lg download-btn" data-target="#click-down" data-toggle="modal"><span class="glyphicon glyphicon-download"></span> 免费下载</button>
      -->
      <button type="button" class="btn btn-success btn-lg download-btn" data-target="#click-down" data-toggle="modal"><span><img src="/app_main_images/download_icon.png" style="margin-top:-5px;"></span> 免费下载</button> 
   </div>
    <div class="intro-right pull-right"></div>
  </div>

</div>


<div class="container">

  <h2 class="slogan">她们正在创造的时尚范儿！</h2>

  <div class="inner">

  <div class="dp-container">
    <% @dapeis.each do |dp|%>
      <% next unless dp %>
      <div class="dp-item">
        <div class="top-part">
          <img alt="<%=dapei_photo_alt(dp)%>" title ="<%=dapei_photo_title(dp)%>" src ="<%=dp.img_url(:scaled_medium)%>">
        </div>
        <div class="foot-part">
          <span>  by </span>
          <span>
            <%=dp.get_user.name%>
          </span>
        </div>
      </div>
    <%-end%>
  </div>

    <div class="comeonbaby">更多时尚范儿，等待你的发现...</div>
    <div class="comeonbtn text-center"><button type="button" class="btn btn-success btn-lg download-btn" data-target="#click-down" data-toggle="modal"><span><img src="/app_main_images/download_icon.png" style="margin-top:-5px;"></span> 立即下载</button></div>

  </div>
</div>

<%= render :partial=>"/layouts/footer"%>

<!-- click-down -->
<div class="modal fade downloadModal" id="click-down" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

        <div class="btn-list">
          <a href="https://itunes.apple.com/us/app/shang-jie-ba/id657031277?ls=1&mt=8" target="_blank" class="btn-download ios" title="App Store下载">App Store下载</a>
          <a href="http://www.shangjieba.com/shangjieba.apk" target="_blank" class="btn-download android" title="下载APK安装包">下载APK安装包</a>
         
          <div class="qr-code">
            <p>
             <a href="https://itunes.apple.com/us/app/shang-jie-ba/id657031277?ls=1&mt=8" target="_blank" title="App Store下载"> 
               <img src="/assets/liantu.png">
             </a> 
            </p> 
          </div>

          <div class="qr-code2">
            <p>
             <a href="http://www.shangjieba.com/shangjieba.apk" target="_blank" title="下载APK安装包">
               <img src="/assets/android_app.png">
             </a> 
            </p>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<!-- end click-down -->

<!-- click-wx -->
<div class="modal fade downloadModal" id="click-wx" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

            <img alt="" class="wx_img" src="/assets/banner/weixin.jpg" width="130" height="130">
            <p> 或者搜索公众账号</p>
            <p> 【上街吧】</p>
      </div>
    </div>
  </div>
</div>
<!-- end click-wx -->

app/views/home/index.html.haml
- cache "home_#{@city_id}" do
  = render "hot_banner"
  = render "hot_baobei"
  = render "hot_shop"
  = render "hot_brand"
  = render "hot_dapei"

-#= render "hot_daren"

-#- unless user_signed_in?
  = render "shared/login_footer" 