config/routes.rb
      post :wxpay
    end
  end

  namespace :manage do
    root to: "home#index"
    resources :friend_apps
    
    resources :synonyms
    resources :posts do
      member do
        get :photo
        post :photo_create
      end
    end

    post "/posts/:id" => "posts#update"
    resources :tags do
      member do
        get :get_desc
      end
    end

    resources :all_tags
    get '/dapeis/queue' => "dapeis#queue"
    get '/collections' => "dapeis#collections"
    get '/selfies' => "dapeis#selfies"
    get '/dapeis/:id/new_comment' => "dapeis#new_comment"
    put '/selfy/:id', to: 'dapeis#selfy_update', as: :selfy
    resources :collections do
      member do
        post :cover_photo # 封面图
      end
      resources :comments, :only => [:index, :create, :destroy], :name_prefix => "item_"
    end

    resources :selfies ,:only =>[:new,:create]
    # resources :dapeis
    resources :dapeis do
      collection do
        get 'all'
      end

      member do
        post 'recommend_star'
        post 'unrecommend_star'
      end
    end

    put "categories/set_app_photo" => "categories#set_app_photo"

    resources :categories do
      collection do
        get :for_select
        get :ajax_select_change
      end

      member do
        get :feature
        post :feature_create
      end
    end
    resources :matters do
      collection do
        get :recommends
        get :brands
        get :tags
        post :recommended
      end
    end

    get 'matters/:id/koutu' => "matters#koutu"
    get 'user_behaviours/:user_id' => "user_behaviours#index"
    get 'user_behaviours/xml_index/:user_token' => "user_behaviours#xml_index"
    resources :user_behaviours
    resources :matter_tags
    resources :meta_tags

    resources :dapei_tags do
      member do
        post :upload
      end
    end

    resources :apps
    resources :photos, only: :destroy
    resources :flinks
    resources :crawler_templates do
      collection do
        get "search_brands"
        get "search_malls"
      end
    end
    resources :users, except: :new do
      member do
        get :set_black
        get :set_v
      end
      resources :messages
    end

    resources :malls
    resources :discounts
    resources :spiders, except: :new do
      member do
        get :start_crawl
        get :start_soldout
        get :update_state
      end
      resources :spider_pages
    end
    post '/spiders/:spider_id/spider_pages' => 'spider_pages#create', :as => 'spider_spider_pages_index'


    resources :tshow_spiders, except: :new do
      member do
        get :start_crawl
      end
    end
    resources :brand_tags
    resources :brands do
      resources :spiders, only: :new
      resources :tshow_spiders, only: :new
      member do
        get :spiders
        post :upload
      end
    end

    resources :shops do
      member do
        get :discounts
      end
    end

    resources :feedbacks
    resources :lotteries

    get "update_category_photo/:category_id/:matter_id" => "categories#set_photo", :as => "update_category_photo"
  end


  namespace :service do
    get "dapei/get_color" => "dapei#get_color"
    get "dapei/template_cut" => "dapei#template_cut"
    get "dapei/cut_templates" => "dapei#cut_templates"
  end

  resources :daren_applies do
    collection do
      get "about_daren"
      get "user_help"
      get "daren_info"
      get "medal_info"
    end
  end  

  scope "sjb" do
    resources :relations

    resources :labels

    resources :policies

    resources :user_devices

    resources :user_exts do
      collection do
        get :new_create
      end
    end

    get "user_exts/new_create/fr/android" => "user_exts#new_create"
    get "user_exts/create_result" => "user_exts#create_result"


    resources :lotteries

    resources :join_lotteries
    get "join_lottery/status" => "join_lotteries#status"
    get "lottery/current" => "lotteries#current"

    get "cj" => "user_exts#cj"
    get "reg" => "user_exts#reg"
    get "daren_apply_status" => "daren_applies#show"

  end

  get "app/test/app_about" => "about#app_about", :as => "app_about"
  get "app/test/app_business" => "about#app_business", :as => "app_business"
  get "web/web_version" => "home#index", :as => "web_version"


  get "weixin/app" => "weixin#app"
  get "weixin/sg_app" => "weixin#sg_app"
  get "weixin/app" => "weixin#app"
  get "app/android" => "weixin#android_download"

  get "about/info/brand_all" => "about#brand_all"

  get "about/info/fashion" => "about#fashion"

  get "about/info/website_map" => "about#website_map"

  get "about/info/trade" => "about#trade"

  get "about/info/member_introduce" => "about#member_introduce"

  get "about/info/get_password" => "about#get_password"

  get "about/info/help" => "about#help"

  get "about/info/report" => "about#report"

  get "about/info/recruitment" => "about#recruitment"

  get "about/info/brand_enter" => "about#brand_enter"

  get "about/info/collaborate" => "about#collaborate"

  get "about/info/advertisement" => "about#advertisement"

  get "about/info/merchant" => "about#merchant"

  get "about/info/contact" => "about#contact"
  get "about/info/cover" => "about#cover"
  get "about/info/mzsm" => "about#mzsm"

  get "about/shangou_option" => "about#shangou_option"

  get "collocations/mask_spec" => "collocations#mask_spec"
  get "collocations/text2image" => "collocations#text2image"

  get "collocations/hot_dapei_tags" => "collocations#hot_dapei_tags"
  get "info/hot_dapei_tags" => "collocations#hot_dapei_tags"
  get "info/publish_dapei_tags" => "collocations#publish_dapei_tags"
  get "info/dapei_themes" => "collocations#dapei_themes"
  get "info/app_banner" => "about#app_banner"
  get "info/app_banner_new" => "about#app_banner_new"
  get "info/dapei_banners" => "about#dapei_banners"

  get "info/daren_policy" => "policies#daren"
  get "info/dapei_tags" => "about#dapei_tags"


  get "info/activity_types" => "discounts#discount_types"

  resources :collocations do
    collection do
      get 'price_range'
      get 'app_template'
    end
  end


  get 'cgi/mystuff.things' => "collocations#mystuff_things"
  get 'cgi/like_matters' => "collocations#like_matters"

  post 'cgi/set.draft' => "collocations#set_draft"
  post 'cgi/template.publish' => "collocations#template_publish"
  post 'cgi/stats.record' => "collocations#stats_record"

  post 'cgi/favorite.add_thing' => "likes#create"
  post 'cgi/favorite.delete_thing' => "collocations#delete_thing"
  post 'cgi/favorite.delete_matter' => "collocations#delete_matter"

  get 'cgi/autocomplete.user_tagging' => "collocations#user_tagging"
  get 'cgi/autocomplete.user_hashtags' => "collocations#user_hastags"
  get 'cgi/autocomplete.price_ranges' => "collocations#price_ranges"
  get 'cgi/autocomplete.category_id_titles' => "collocations#category_id_titles"
  get 'cgi/autocomplete.categories' => "collocations#categories"
  get 'cgi/autocomplete.editor' => "collocations#editor"
  get 'cgi/template.load' => "collocations#template_load"
  get 'cgi/search.editor_things' => "collocations#editor_things"
  get 'cgi/search.sponsored_things' => "collocations#sponsored_things"
  get 'cgi/search.templates' => "collocations#templates"
  # post "/cgi/login.login" => "collocations#login_login"
  # get 'cgi/login' => "collocations#login"
  post "cgi/set.publish" => "collocations#publish"
  get "cgi/autocomplete.shop" => "collocations#shop"
  get 'cgi/collection.load' => "collocations#collection_load"

  get 'cgi/set.embed_html' => "collocations#embed_html"
  get 'cgi/autocomplete.tag_trends' => "collocations#tag_trends"
  get 'cgi/set.load' => "collocations#cgi_set_load"
  get 'cgi/set' => "collocations#cgi_set"

  get "dapeis/cgi/autocomplete.shop" => "collocations#shop"
  post "dapeis/cgi/stats.record" => "collocations#stats_record"
  get "dapeis/cgi/collection.load" => "collocations#collection_load"
  post 'cgi/comment.add' => "collocations#comment_add"

  get "cgi/item" => "collocations#item"
  get "cgi/collection.get" => "collocations#collection_get"
  get "cgi/mystuff.sets" => "collocations#mystuff_sets"
  get "cgi/mystuff.drafts" => "collocations#mystuff_drafts"
  get "cgi/mystuff.templates" => "collocations#mystuff_templates"
  get "uploads//cgi/img-thing/mask_spec/:spec/size/orig/tid/:image_name" => "collocations#mask_sepc"

  post "cgi/app.save_mask" => "collocations#save_mask"
  get "cgi/app.get_masks" => "collocations#get_masks"
  get "cgi/cut_templates" => "collocations#cut_templates"

  scope "admin" do
    resources :flinks
  end

  get "brands/info/web_index" => "brands#web_index", :as => "brands_web_index_old"
  get "brands/info/:id" => "brands#web_show", :as => "brands_web_show_old"

  resources :brands, :only => [:show]

  resources :recommends, :except => [:index]

  get "categories/index"
  get "about/feedback" => "about#feedback", :as => "feedback"
  post "about/send_feedback" => "about#create_feedback", :as => "create_feedback"
  get "about/version" => "about#version", :as => "version"
  get "about/wanhuir_version" => "about#wanhuir_version", :as => "wanhuir_version"
  get "about/shangou_version" => "about#shangou_version", :as => "shangou_version"

  get "about/info/about_me" => "about#about_me", :as => "about_me"
  get "about/apps" => "about#apps", :as => "abount_apps"
  get "about/download_app" => "about#download_app", :as => "download_app"

  get "/posts/new_index" => "posts#new_index"
  resources :posts do
    resources :comments, :only => [:index, :create, :destroy], :name_prefix => "post_"
  end

  resources :feedbacks

  get "notifications/index"
  get "notifications/index_new" => "notifications#index1"
  get "notifications/index_notify" => "notifications#notify"
  #get ':id'=>'shops#show', :constraints => { :id => /[A-Za-z0-9\-_]+/ }

  post 'shops/:id/update' => "shops#update"
  post 'devices/register' => "devices#register"

  get 'items/index_all' => 'items#index_all', :as => "items_all"

app/models/about.rb
# -*- encoding : utf-8 -*-
class About
  attr_accessor :name
  attr_accessor :url
  attr_accessor :i
  attr_accessor :childs
  attr_accessor :action
  # initialize
  class << self
  	def all
  	  # a  = []
  	  # b1 = new
  	  as = [{name:"新手上路",childs:[["购物流程","/about/info/trade","trade"],["会员介绍","/about/info/member_introduce","member_introduce"],["找回密码","/about/info/get_password","get_password"],["帮助中心","/about/info/help","help"]]},
  			{name:"关于我们",childs:[["上街吧介绍","/about/info/about_me","about_me"],["媒体报道","/about/info/report","report"],["招聘信息","/about/info/recruitment","recruitment"],["联系我们","/about/info/contact","contact"]]},
  			{name:"商务合作",childs:[["品牌入驻","/about/info/brand_enter","brand_enter"],["媒体合作","/about/info/collaborate","collaborate"],["广告投放","/about/info/advertisement","advertisement"],["商家中心","/about/info/merchant","merchant"]]},
  			{name:"网站导航",childs:[["品牌大全","/about/info/brand_all","brand_all"],["覆盖城市","/about/info/cover","cover"],["流行风格","/about/info/fashion","fashion"],["网站地图","/about/info/website_map","website_map"]]}]
  	  # b1.name = "新手上路"
  	  # b1.url = ""
  	  i = 0
  	  as.collect{|a|
  	  	b = new
  	  	b.i = i
  	  	b.name = a[:name]
  	  	b.childs=[]
  	  	a[:childs].each{|a1|
  	  	  a2 = new
  	  	  a2.name = a1[0]
  	  	  a2.url = a1[1]
          a2.action = a1[-1]
  	  	  # a2.url += "?i=#{i}" if a2.url != '#'
  	  	  a2.i   = i
  	  	  b.childs << a2
  	  	}
  	  	i += 1
		b  	  	
  	  }
  	end
  end
end

app/helpers/about_helper.rb
# -*- encoding : utf-8 -*-
module AboutHelper
end

app/views/about/_download.html.haml
.download_area
  -#.hd
    %h3 马上下载iphone app
  .bd
    .download_btn
      %a{:href => "https://itunes.apple.com/us/app/shang-jie-ba/id657031277?ls=1&mt=8"} 下载iphone app
    .download_qr
      %a{:href => "https://itunes.apple.com/us/app/shang-jie-ba/id657031277?ls=1&mt=8", :rel=>"nofollow"}
        %img{:height => "44", :src => "/assets/liantu.png"}/

app/views/about/advertisement.html.haml
= @site_help.content.html_safe

app/views/about/app_business.html.erb
<div class="container">
  <div class="row inner">

    <div class="col-xs-9 info-text">
      <h2>商务合作</h2>
      <p>
        品牌合作、资源置换等，联系邮箱：chamy@shangjieba.com
      </p>
    </div>

    <div class="col-xs-2 pull-right">
        <ul class="nav">
          <li> <a href="<%= app_about_path %>">关于我们</a> </li>
          <li> <a href="<%= app_business_path %>">商务合作</a> </li>
        </ul>
    </div>
    <div class="backg-footer">
      <img src="/app_main_images/people2.png">
    </div>

  </div>
</div>

app/views/about/brand_all.html.haml
.alphabet-list
  - for i in 65..90
    %a{href:"/about/info/brand_all?q="+i.chr,class:"#{params[:q] == i.chr ? "about-q-underline" : ""}"}
      %b=i.chr
- if @brand_all
  .about-area
    %ul
      - for s in @brand_all
        %li
          = link_to s.name, search_path("", "", "", s.name, "", "")
          / %a{:href => "#{city_path(city.pinyin)}"} #{city.name}

app/views/about/brand_enter.html.haml
= @site_help.content.html_safe

app/views/about/collaborate.html.haml
= @site_help.content.html_safe

app/views/about/cover.html.haml
.alphabet-list
  - for i in 65..90
    %a{href:"/about/info/cover?q="+i.chr,class:"#{params[:q] == i.chr ? "about-q-underline" : ""}"}
      %b=i.chr
- if @areas
  .about-area
    %ul
      - for city in @areas
        %li
          %a{:href => "#{city_path(city.pinyin)}"} #{city.name}

app/views/about/fashion.html.haml
<div style="font-size:20px;text-align;margin:40px">准备中...</div>

app/views/about/feedback.html.haml
.layer_box
  -#{:style => "left:200px; top:200px; width:760px; height:460px;"}
  -#.layer_bd
  .hd
    %h2 意见反馈
    %a.close{:href => "#"}
  .bd
    .about_bd#feedback_div
      = form_tag "/feedbacks", :method => :post, :remote => true do
        %br
        = label_tag :content, "反馈意见内容"
        = text_area_tag :content, "", rows: 4, style: "width: 450px"
        = label_tag :qq, "你的QQ号码"
        = text_field_tag :qq
        = label_tag :email, "输入你的电子邮箱"
        = text_field_tag :email
        = label_tag :telephone, "你的手机号码"
        = text_field_tag :telephone
        %label
        = submit_tag "submit"
      %br
      .title
        .col
          %p
            %a{:href => "http://weibo.com/u/3985893887", :rel=>"nofollow"}关注我们的新浪微博
          %p
            %a{:href => "http://weibo.com/u/3985893887", :rel=>"nofollow"}  
              %img{:height => "44", :src => "/assets/sina-weibo.png", :width => "109"}/ 
        .col
          %p 微信号
          %p shangjiezhushou
          %p 扫描二维码添加
        .col
          %img{:src => "http://t2.qpic.cn/mblogpic/73149a6d847e3dfa9c02/460", :alt=>"上街吧微信"}
    

app/views/about/help.html.haml
= @site_help.content.html_safe

app/views/about/mzsm.html.haml
.wrapper  
  %div{style:"margin:40px 250px;font-size:16px;color:#000;line-height:26px; box-shadow: 1px 2px 2px 2px #999;-webkit-box-shadow: 1px 2px 2px 2px #999;-moz-box-shadow: 1px 2px 2px 2px #999;padding:30px"}
    %h3{style:"text-align:center;"} 免责声明
    %div
      1、本站所展示的商品都在来源于互联网，内容真实性、准确性和合法性由发布商家负责。上街吧应对此不承担法律责任。
    %div
      2、如果本站产品侵犯您的版权，请联系上街吧(021-54855946)。我们会在24小时内审核处理。
    %div
      3、网站留言评论仅代表商家、用户的个人观点，如果不需要显示的留言或评论，请联系上街吧(021-54855946)删除。	
    %div
      4、上街吧只提供商品信息，一切交易将视为客户自行自愿交易，对交易产生问题由交易双方自行负责，上街吧对此不承担任何保证责任。
    %div{style:"text-align:right"}
      %img{src:"/assets/newweb/logo.png"}

app/views/about/report.html.haml
= @site_help.content.html_safe

app/views/about/trade.html.haml
= @site_help.content.html_safe

app/views/about/website_map.html.haml
.website_map_nav 频道
%table.website_map_table
  %tr
    %td.left 
      首页
    %td.right
      %div 周边热点
      %div 在售新品
      %div 特卖优惠
      %div 品牌汇
      %div 搭配记
.split
.website_map_nav 分类
%table.website_map_table
  %tr
    %td.left 
      上装
    %td.right
      %div 背心
      %div T恤
      %div 小西装
      %div 开衫
.split
%table.website_map_table
  %tr
    %td.left 
      裤装
    %td.right
.split
%table.website_map_table
  %tr
    %td.left 
      裙装
    %td.right
.split
%table.website_map_table
  %tr
    %td.left 
      内衣
    %td.right
.split
%table.website_map_table
  %tr
    %td.left 
      鞋子
    %td.right 
.split
%table.website_map_table
  %tr
    %td.left 
      包包
    %td.right  
.website_map_nav 服务
%table.website_map_table
  %tr
    %td.left2 
      新手上路
    %td.right
      %div 购物流程
      %div 会员介绍
      %div 找回密码
      %div 帮助中心
.split  
%table.website_map_table
  %tr
    %td.left2 
      关于我们
    %td.right
      %div 上街吧介绍
      %div 媒体报道
      %div 招聘信息
      %div 联系我们
.split                
%table.website_map_table
  %tr
    %td.left2 
      商务合作
    %td.right
      %div 品牌入驻
      %div 媒体合作
      %div 广告投放
      %div 商家中心
.split                           
%table.website_map_table
  %tr
    %td.left2 
      网站导航
    %td.right
      %div 品牌大全
      %div 覆盖城市
      %div 流行风格
      %div 网站导航
.split                 
 